import Link from "next/link";
import estilos from "./landing.module.css";

export default function Home() {
  return <main className={estilos.pagina}>
    <header className={estilos.cabecalho}><Link href="/" className={estilos.marca}>Escritório Dativo<span>OAB Paraná · Advocacia Dativa</span></Link><nav className={estilos.navegacao} aria-label="Navegação principal"><a href="#o-que-e">O que é</a><a href="#responsabilidades">Responsabilidades</a><a href="#o-caso">O caso</a><a href="#duvidas">Dúvidas</a></nav><Link href="/entrar" className={estilos.entrar}>Entrar</Link></header>
    <section className={estilos.abertura} id="o-que-e"><div className={estilos.aberturaTexto}><p className={estilos.sobrelinha}>Ambiente profissional</p><h1>Escritório<br />Dativo</h1><p className={estilos.chamada}>O ambiente de trabalho da advocacia dativa no Paraná.</p><p className={estilos.introducao}>Nomeações, atendimento, processo, documentos, pesquisa, formação e honorários convivem no mesmo ambiente. O sistema organiza o trabalho; o advogado continua responsável por cada ato.</p><div className={estilos.acoesAbertura}><Link href="/entrar" className={estilos.entrarPrincipal}>Entrar no Escritório Dativo <span aria-hidden="true">→</span></Link></div><p className={estilos.avisoDemo}>Ambiente de demonstração. Todos os dados desta página são fictícios.</p></div><aside className={estilos.hoje}><div className={estilos.hojeCabecalho}><div><p>Quarta-feira, 16 de setembro</p><h2>Hoje no escritório</h2></div><span>DEMO</span></div><ol className={estilos.filaHoje}><li><span className={estilos.marcadorAtencao}/><div><strong>Prazo informado</strong><p>Manifestação em contestação</p></div><small>A conferir no processo oficial</small></li><li><span className={estilos.marcadorAzul}/><div><strong>Audiência</strong><p>Conciliação · 14h30</p></div><small>2º JEC de Curitiba</small></li><li><span className={estilos.marcadorOk}/><div><strong>Documentos recebidos</strong><p>Comprovantes enviados pela assistida</p></div><small>Revisar 3 arquivos</small></li></ol></aside></section>
    <section className={estilos.fluxo}><div className={estilos.tituloSecao}><p className={estilos.sobrelinha}>Do recebimento ao pós-atuação</p><h2>O caso permanece inteiro.</h2></div><div className={estilos.linhasFluxo}>{[["01","Nomeação","O registro abre o caso com os pontos que exigem conferência."],["02","Atendimento","Comunicação e documentos chegam vinculados ao contexto."],["03","Atuação","Tarefas, pesquisa e peças deixam histórico rastreável."],["04","Encerramento","Certidões e honorários preservam o pós-atuação."]].map(([numero,titulo,texto])=><article key={numero}><span>{numero}</span><h3>{titulo}</h3><p>{texto}</p></article>)}</div></section>
    <section className={estilos.responsabilidades} id="responsabilidades"><div className={estilos.tituloSecao}><p className={estilos.sobrelinha}>Tecnologia com limite claro</p><h2>O sistema apoia. A responsabilidade permanece profissional.</h2></div><p className={estilos.notaResponsabilidades}>A plataforma não substitui Projudi, PJe ou qualquer sistema judicial oficial. Também não protocola, envia mensagens ou toma decisões de forma autônoma.</p></section>
    <section className={estilos.caso} id="o-caso"><div className={estilos.casoIntroducao}><p className={estilos.sobrelinha}>Uma prévia de caso</p><h2>Contexto suficiente para a próxima providência.</h2><p>Informações processuais, contato, documentos e pesquisa permanecem ligados ao mesmo caso.</p><Link href="/entrar" className={estilos.linkCaso}>Entrar para acessar o escritório <span aria-hidden="true">→</span></Link></div><div className={estilos.previaCaso}><div className={estilos.previaTopo}><div><p>CASO · DADOS FICTÍCIOS</p><h3>Marina A. · Responsabilidade civil</h3><span>2º Juizado Especial Cível de Curitiba</span></div><b>A conferir</b></div></div></section>
    <section className={estilos.duvidas} id="duvidas"><div className={estilos.tituloSecao}><p className={estilos.sobrelinha}>Dúvidas frequentes</p><h2>Limites e funcionamento, sem promessas implícitas.</h2></div><div className={estilos.listaDuvidas}><Duvida pergunta="O sistema substitui Projudi ou PJe?">Não. O escritório organiza o trabalho profissional e não substitui sistemas judiciais oficiais.</Duvida><Duvida pergunta="O sistema conta prazos automaticamente?">Toda data identificada precisa ser conferida no processo oficial.</Duvida><Duvida pergunta="O sistema envia mensagens ou petições sozinho?">Não por padrão. A ação expressa do advogado continua necessária.</Duvida></div></section>
    <section className={estilos.chamadaFinal}><div><p className={estilos.sobrelinha}>Acesso profissional</p><h2>Seu trabalho dativo, com o caso no centro.</h2></div><Link href="/entrar" className={estilos.entrarFinal}>Entrar no Escritório Dativo <span aria-hidden="true">→</span></Link></section><footer className={estilos.rodape}><strong>Escritório Dativo</strong><span>OAB Paraná · Advocacia Dativa</span><small>Ambiente de demonstração · dados fictícios</small></footer>
  </main>;
}
function Duvida({ pergunta, children }: { pergunta: string; children: React.ReactNode }) { return <details><summary>{pergunta}<span aria-hidden="true">+</span></summary><p>{children}</p></details>; }
